# TODO: Rewrite all these controls to match the versions for the COTS spectrometer,
# rather than the versions for the RFSoC


# Global setting trees for the Pulse Frequency Sweep and Spin Echo experiment settings
sweep_list = [
    "Pulse Sweep",
    "Phase Sweep",
    "Rabi",
    "Inversion Sweep",
    "Period Sweep",
    "Hahn Echo",
    "EDFS",
    "Freq Sweep",
    "CPMG",
    "Gain",
    "DEER",
    "Temp"
]

bimod_sweep_list = [
    "A Pulse Sweep",
    "B Pulse Sweep",
    "Both Pulse Sweep",
    "B Rabi",
    "Period Sweep",
    "Hahn Echo",
    "EDFS",
    "A Freq Sweep",
    "B Freq Sweep",
    "Both Freq Sweep",
    "DEER",
]

EXPERIMENT_TEMPLATES = {
    "Pulse Frequency Sweep": {
        "groups": {
            "Main": [
                {
                    "display": "Frequency",
                    "key": "freq",
                    "type": "double_spin",
                    "min": 50.0,
                    "max": 14999.0,
                    "default": 3900.0,
                },
                {
                    "display": "Gain",
                    "key": "gain",
                    "type": "spin",
                    "min": 0,
                    "max": 32500,
                    "default": 32500,
                },
                {
                    "display": "Avg",
                    "key": "soft_avgs",
                    "type": "spin",
                    "min": 1,
                    "max": 1000000,
                    "default": 100,
                },
                {
                    "display": "Dir and Name",
                    "key": ["save_dir", "file_name"],
                    "type": "composite",
                    "default": ["", ""],
                },
                {
                    "display": "Experiment",
                    "key": "psexpt",
                    "type": "combo",
                    "options": ["Freq Sweep", "Field Sweep"],
                    "default": "Freq Sweep",
                },
                {
                    "display": "Sweep start, end, step",
                    "key": ["sweep_start", "sweep_end", "sweep_step"],
                    "type": "composite",
                    "default": [3850.0, 3950.0, 2.0],
                },
            ],
            "Readout": [
                {
                    "display": "Time Offset",
                    "key": "h_offset",
                    "type": "double_spin",
                    # "min": -10000.0,
                    # "max": 10000.0,
                    "default": -0.125,
                },
                {
                    "display": "Readout Length",
                    "key": "readout_length",
                    "type": "double_spin",
                    "min": 0.0,
                    "max": 5.0,
                    "default": 0.2,
                },
                {
                    "display": "Loopback",
                    "key": "loopback",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Integral only",
                    "key": "integrate",
                    "type": "check",
                    "default": True,
                },
            ],
            "Magnet": [
                {
                    "display": "Field, Scale, I limit",
                    "key": ["field", "gauss_amps", "current_limit"],
                    "type": "composite",
                    "default": [0.0, 276.0, 3.5],
                },
                {
                    "display": "Turn field off after sweep?",
                    "key": "turn_off",
                    "type": "check",
                    "default": True,
                },
            ],
            "Temperature": [
                {
                    "display": "Set Temp, Ramp, Heater",
                    "key": ["set_temp", "temp_ramp", "heater_on"],
                    "type": "composite",
                    "default": [False, True, False],
                },
                {
                    "display": "Setpoint (K)",
                    "key": "temp",
                    "type": "double_spin",
                    "min": 1.0,
                    "max": 325,
                    "default": 4,
                },
                {
                    "display": "Use Lakeshore?",
                    "key": "use_temp",
                    "type": "check",
                    "default": False,
                },
            ],
            "Uncommon Settings": [
                {
                    "display": "Repetition time",
                    "key": "period",
                    "type": "double_spin",
                    "min": 0.1,
                    # "max": 2000000000.0,
                    "default": 10.0,
                },
                {
                    "display": "Ch1 90 Pulse",
                    "key": "pulse1_1",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 652100.0,
                    "default": 50.0,
                },
                {
                    "display": "Reps",
                    "key": "ave_reps",
                    "type": "spin",
                    "min": 1,
                    # "max": 1000,
                    "default": 1,
                },
                {
                    "display": "Wait Time",
                    "key": "wait",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 20.0,
                    "default": 0.3,
                },
                {
                    "display": "Switch Offset (us)",
                    "key": "sw_offset",
                    "type": "double_spin",
                    "min": -1e5,
                    "max": 1e5,
                    "default": -0.45,
                },
                {
                    "display": "DAC Ch",
                    "key": "dac_ch",
                    "type": "combo",
                    "options": ["B", "A"],
                    "default": "B",
                },
            ],
            "Utility Settings": [
                {
                    "display": "Use PSU?",
                    "key": "use_psu",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Moku Setup",
                    "key": "moku",
                    "type": "combo",
                    "options": ['Cryostat', 'Bench', 'None'],
                    "default": "Cryostat",
                },
                {
                    "display": "Turn laser on? (Bench Moku)",
                    "key": "laser_on",
                    "type": "check",
                    "default": True,
                },
            ],
            "Never Change": [
                {
                    "display": "Phase",
                    "key": "phase",
                    "type": "double_spin",
                    "min": 0.0,
                    "max": 360.0,
                    "default": 0.0,
                },
                {
                    "display": "Averaging Time (s)",
                    "key": "sltime",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 20.0,
                    "default": 0.0,
                },
                {
                    "display": "Sub Method",
                    "key": "subtract",
                    "type": "combo",
                    "options": ["Phase", "None"],
                    "default": "None",
                },
            ],
        }
    },
    "Spin Echo": {
        "groups": {
            "Main": [
                {
                    "display": "Ch1 Freq",
                    "key": "freq",
                    "type": "double_spin",
                    "min": 50.0,
                    "max": 14999.0,
                    "default": 3902.0,
                    "tool tip": "Helpful information",
                },
                {
                    "display": "Gain",
                    "key": "gain",
                    "type": "spin",
                    "min": 0,
                    "max": 32500,
                    "default": 32500,
                    "tool tip": "Helpful information",
                },
                {
                    "display": "Repetition time (us)",
                    "key": "period",
                    "type": "double_spin",
                    "min": 0.1,
                    # "max": 2000000000.0,
                    "default": 200.0,
                    "tool tip": "Helpful information",
                },
                {
                    "display": "Ave",
                    "key": "soft_avgs",
                    "type": "spin",
                    "min": 1,
                    "max": 10000000,
                    "default": 100,
                },
                {
                    "display": "Dir and Name",
                    "key": ["save_dir", "file_name"],
                    "type": "composite",
                    "default": ["", ""],
                },
                {
                    "display": "Reps",
                    "key": "ave_reps",
                    "type": "spin",
                    "min": 1,
                    # "max": 1000,
                    "default": 1,
                },
                {
                    "display": "Experiment",
                    "key": "expt",
                    "type": "combo",
                    "options": sweep_list,
                    "default": "Hahn Echo",
                },
                {
                    "display": "Sweep start, end, step",
                    "key": ["sweep_start", "sweep_end", "sweep_step"],
                    "type": "composite",
                    "default": [150.0, 1000.0, 50.0],
                },
            ],
            "Pulse": [
                {
                    "display": "Ch1 Delay",
                    "key": "delay",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 652100,
                    "default": 150.0,
                },
                {
                    "display": "90 Pulse",
                    "key": "pulse1_1",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 652100,
                    "default": 50.0,
                },
                {
                    "display": "Nut. Delay (us)",
                    "key": "nutation_delay",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 655360,
                    "default": 5000.0,
                },
                {
                    "display": "Nut. Pulse Width",
                    "key": "nutation_length",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 655360,
                    "default": 0.0,
                },
                {
                    "display": "# 180 Pulses",
                    "key": "pulses",
                    "type": "spin",
                    "min": 1,
                    "max": 256,
                    "default": 1,
                },
            ],
            "Readout": [
                {
                    "display": "Time Offset (us)",
                    "key": "h_offset",
                    "type": "double_spin",
                    "min": -1e5,
                    "max": 1e5,
                    "default": -0.025,
                },
                {
                    "display": "Readout Length (us)",
                    "key": "readout_length",
                    "type": "double_spin",
                    "min": 0.0,
                    "max": 5.0,
                    "default": 0.2,
                },
                {
                    "display": "Loopback",
                    "key": "loopback",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Integral only",
                    "key": "integrate",
                    "type": "check",
                    "default": True,
                },
            ],
            "Magnet": [
                {
                    "display": "Magnetic Field (G)",
                    "key": "field",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 10000,
                    "default": 0.0,
                },
                {
                    "display": "Magnet Scale (G/A)",
                    "key": "gauss_amps",
                    "type": "double_spin",
                    "min": 0.001,
                    # "max": 100000.0,
                    "default": 270.0,
                },
                {
                    "display": "Current limit (A)",
                    "key": "current_limit",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 10.0,
                    "default": 3.5,
                },
                {
                    "display": "Turn field off after sweep?",
                    "key": "turn_off",
                    "type": "check",
                    "default": True,
                },
            ],
            "Temperature": [
                {
                    "display": "Set Temp, Ramp, Heater",
                    "key": ["set_temp", "temp_ramp", "heater_on"],
                    "type": "composite",
                    "default": [False, True, False],
                },
                {
                    "display": "Setpoint (K)",
                    "key": "temp",
                    "type": "double_spin",
                    "min": 1.0,
                    "max": 325,
                    "default": 4,
                },
                {
                    "display": "Use Lakeshore?",
                    "key": "use_temp",
                    "type": "check",
                    "default": False,
                },
            ],
            "Second Sweep": [
                {
                    "display": "Second sweep?",
                    "key": "sweep2",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Experiment 2",
                    "key": "expt2",
                    "type": "combo",
                    "options": sweep_list,
                    "default": "Hahn Echo",
                },
                {
                    "display": "Sweep 2 start, end, step",
                    "key": ["sweep2_start", "sweep2_end", "sweep2_step"],
                    "type": "composite",
                    "default": [0, 0, 0],
                },
            ],
            "Uncommon": [
                {
                    "display": "Wait Time (s)",
                    "key": "wait",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 20.0,
                    "default": 0.2,
                },
                {
                    "display": "DEER Freq",
                    "key": "freq2",
                    "type": "double_spin",
                    "min": 50.0,
                    "max": 14999.0,
                    "default": 3902.0,
                    "tool tip": "Helpful information",
                },
                {
                    "display": "Second Delay",
                    "key": "tau",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 652100,
                    "default": 150.0,
                },
                {
                    "display": "DEER Delay",
                    "key": "DEER_delay",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 652100,
                    "default": 150.0,
                },
                {
                    "display": "DEER Pulse",
                    "key": "pulse2_2",
                    "type": "double_spin",
                    "min": 0,
                    # "max": 652100,
                    "default": 50.0,
                },
            ],
            "Utility Settings": [
                {
                    "display": "Use PSU?",
                    "key": "use_psu",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Moku Setup",
                    "key": "moku",
                    "type": "combo",
                    "options": ['Cryostat', 'Bench', 'None'],
                    "default": "Cryostat",
                },
                {
                    "display": "Turn laser on? (Bench Moku)",
                    "key": "laser_on",
                    "type": "check",
                    "default": True,
                },
                {
                    "display": "Switch Offset (us)",
                    "key": "sw_offset",
                    "type": "double_spin",
                    "min": -1e5,
                    "max": 1e5,
                    "default": -0.45,
                },
            ],
            "Never Change": [
                {
                    "display": "Phase",
                    "key": "phase",
                    "type": "double_spin",
                    "min": 0.0,
                    "max": 360.0,
                    "default": 0.0,
                },
                {
                    "display": "Auto Phase Sub",
                    "key": "phase_sub",
                    "type": "check",
                    "default": False,
                },
                {
                    "display": "Sub Method",
                    "key": "subtract",
                    "type": "combo",
                    "options": ["Phase", "None"],
                    "default": "Phase",
                },
                {
                    "display": "Averaging Time (s)",
                    "key": "sltime",
                    "type": "double_spin",
                    "min": 0.0,
                    # "max": 20.0,
                    "default": 0.0,
                },
                {
                    "display": "Ch1 180 Pulse Mult",
                    "key": "mult1",
                    "type": "double_spin",
                    "min": 0,
                    "max": 652100,
                    "default": 1.0,
                },
                {
                    "display": "DAC Ch",
                    "key": "dac_ch",
                    "type": "combo",
                    "options": ["B", "A"],
                    "default": "B",
                },
            ],
        }
    },
}